<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../common.props" />
  <PropertyGroup>
    <RootNamespace>H.Setting.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\H.Setting.Application.Contracts\H.Setting.Application.Contracts.csproj" />
    <ProjectReference Include="..\H.Setting.EntityFrameworkCore\H.Setting.EntityFrameworkCore.csproj" />
  </ItemGroup>

</Project>
