<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../common.props" />
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Application" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Utils\H.Extensions.System\H.Extensions.System.csproj" />
    <ProjectReference Include="..\H.SystemPortal.Application.Contracts\H.SystemPortal.Application.Contracts.csproj" />
  </ItemGroup>
</Project>
