<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\common.props" />
  <ItemGroup>
    <ProjectReference Include="..\..\Common\H.LowCode.Application.Contracts\H.LowCode.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\Common\H.LowCode.MetaSchema.RenderEngine\H.LowCode.MetaSchema.RenderEngine.csproj" />
  </ItemGroup>
</Project>