<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../common.props" />
  <PropertyGroup>
    <RootNamespace>H.SupplyChain.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\H.SupplyChain.Application.Contracts\H.SupplyChain.Application.Contracts.csproj" />
    <ProjectReference Include="..\H.SupplyChain.EntityFrameworkCore\H.SupplyChain.EntityFrameworkCore.csproj" />
  </ItemGroup>

</Project>