<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../common.props" />
  <PropertyGroup>
    <RootNamespace>H.Assistant.Application.Contracts</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../Utils/H.Abp.Application.Contracts/H.Abp.Application.Contracts.csproj" />
  </ItemGroup>
</Project>
