<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
	
  <Import Project="../../../common.props" />
	
  <PropertyGroup>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>
	
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
  </ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\..\..\Utils\H.Abp.HttpClientProxy\H.Abp.HttpClientProxy.csproj" />
    <ProjectReference Include="..\..\..\LowCode\RenderEngine\H.LowCode.RenderEngine\H.LowCode.RenderEngine.csproj" />
  </ItemGroup>
  <!-- 防止 Release/AOT 裁剪掉仅被字符串反射引用的组件类型 -->
  <ItemGroup>
    <TrimmerRootAssembly Include="H.LowCode.Components" />
  </ItemGroup>
</Project>