<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../common.props" />
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Autofac.WebAssembly" />
    <PackageReference Include="Volo.Abp.Http.Client" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\H.Account.Application.Contracts\H.Account.Application.Contracts.csproj" />
  </ItemGroup>
</Project>