<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../common.props" />
  <ItemGroup>
    <ProjectReference Include="../../../Utils/H.Abp.HttpClientProxy/H.Abp.HttpClientProxy.csproj" />
    <ProjectReference Include="..\H.Account.Application.Contracts\H.Account.Application.Contracts.csproj" />
  </ItemGroup>
</Project>