<Project Sdk="Microsoft.NET.Sdk.Web">

	<Import Project="../../../../common.props" />

	<PropertyGroup>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
	<PackageReference Include="Volo.Abp.Autofac" />
	<PackageReference Include="Volo.Abp.AspNetCore.Mvc" />
  </ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Services\Account\H.Account.Application\H.Account.Application.csproj" />
    <ProjectReference Include="..\H.Account.Host.Client\H.Account.Host.Client.csproj" />
  </ItemGroup>

</Project>
