<Project Sdk="Microsoft.NET.Sdk.Web">

	<Import Project="../../../../common.props" />

	<PropertyGroup>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Volo.Abp.Autofac" />
	<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
  </ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="../../../../Services/Account/H.Account.HttpApi/H.Account.HttpApi.csproj" />
    <ProjectReference Include="../H.Account.Host.Client/H.Account.Host.Client.csproj" />
  </ItemGroup>

</Project>
