<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\common.props" />

  <ItemGroup>
    <ProjectReference Include="..\..\..\Utils\H.Util.Blazor\H.Util.Blazor.csproj" />
    <ProjectReference Include="..\..\..\LowCode\Common\H.LowCode.ComponentBase\H.LowCode.ComponentBase.csproj" />
  </ItemGroup>

</Project>
