<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\common.props" />
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Extensions" />
    <PackageReference Include="Volo.Abp.Core" />
    <PackageReference Include="Volo.Abp.Ddd.Application" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\H.LowCode.Application.Contracts\H.LowCode.Application.Contracts.csproj" />
  </ItemGroup>
</Project>