<Project Sdk="Microsoft.NET.Sdk.Razor">
  <Import Project="..\..\..\common.props" />
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\H.AppDrawer.Model\H.AppDrawer.Model.csproj" />
    <ProjectReference Include="..\..\..\Utils\H.Util.Base\H.Util.Base.csproj" />
    <ProjectReference Include="..\..\..\Utils\H.Util.Blazor\H.Util.Blazor.csproj" />
  </ItemGroup>
</Project>