// <auto-generated />
using System;
using H.LowCode.DbMigrator;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace H.LowCode.DbMigrator.Migrations
{
    [DbContext(typeof(MigratorDbContext))]
    [Migration("20251123125049_Attendance")]
    partial class Attendance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("H.LowCode.DynamicEntity.tb_check", b =>
                {
                    b.Property<string>("f_id")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("f_checklocation")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("f_checktime")
                        .HasColumnType("datetime2");

                    b.Property<int>("f_checktype")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("f_deptid")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("f_userid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("f_id");

                    b.ToTable("tb_check", (string)null);
                });

            modelBuilder.Entity("H.LowCode.DynamicEntity.tb_leave_request", b =>
                {
                    b.Property<string>("f_id")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("f_approve_remark")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("f_approve_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("f_approver")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("f_create_time")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("f_days")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("f_deptid")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("f_end_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("f_leave_type")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("f_reason")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("f_start_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("f_status")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("f_userid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("f_id");

                    b.ToTable("tb_leave_request", (string)null);
                });

            modelBuilder.Entity("H.LowCode.DynamicEntity.tb_overtime_request", b =>
                {
                    b.Property<string>("f_id")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("f_approve_remark")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("f_approve_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("f_approver")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("f_create_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("f_deptid")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("f_end_time")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("f_hours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("f_overtime_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("f_overtime_type")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("f_reason")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("f_start_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("f_status")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("f_userid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("f_id");

                    b.ToTable("tb_overtime_request", (string)null);
                });

            modelBuilder.Entity("H.LowCode.DynamicEntity.tb_test1", b =>
                {
                    b.Property<string>("f_id")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("f_field1")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("f_field10")
                        .HasColumnType("datetime2");

                    b.Property<string>("f_field11")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("f_field12")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("f_field13")
                        .HasColumnType("datetime2");

                    b.Property<int>("f_field2")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("f_field3")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("f_field4")
                        .HasColumnType("bit");

                    b.Property<int?>("f_field5")
                        .HasColumnType("int");

                    b.Property<string>("f_field6")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("f_field7")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.PrimitiveCollection<string>("f_field8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("f_field9")
                        .HasColumnType("bit");

                    b.HasKey("f_id");

                    b.ToTable("tb_test1", (string)null);
                });

            modelBuilder.Entity("H.LowCode.DynamicEntity.tb_test2", b =>
                {
                    b.Property<string>("f_id")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("f_field1")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("f_field2")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("f_field3")
                        .HasColumnType("bit");

                    b.HasKey("f_id");

                    b.ToTable("tb_test2", (string)null);
                });

            modelBuilder.Entity("H.LowCode.DynamicEntity.tb_test3", b =>
                {
                    b.Property<string>("f_id")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("f_field1")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("f_id");

                    b.ToTable("tb_test3", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
