<Project Sdk="Microsoft.NET.Sdk.Web">
  <Import Project="..\..\..\common.props" />
  <PropertyGroup>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
    <PackageReference Include="Volo.Abp.Autofac" />
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\H.LowCode.Host.All.Client\H.LowCode.Host.All.Client.csproj" />
    <!-- Account 模块 -->
    <ProjectReference Include="..\..\..\Services\Account\H.Account.Application\H.Account.Application.csproj" />
    <!-- Organization 模块 -->
    <ProjectReference Include="..\..\..\Services\Organization\H.Organization.Application\H.Organization.Application.csproj" />
    <!-- DesignEngine 模块 -->
    <ProjectReference Include="..\..\..\LowCode\Common\H.LowCode.Application\H.LowCode.Application.csproj" />
    <ProjectReference Include="..\..\..\LowCode\DesignEngine\H.LowCode.DesignEngine.Application\H.LowCode.DesignEngine.Application.csproj" />
    <ProjectReference Include="..\..\..\LowCode\DesignEngine\H.LowCode.DesignEngine.EntityFrameworkCore\H.LowCode.DesignEngine.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\LowCode\DesignEngine\H.LowCode.DesignEngine.Repository.JsonFile\H.LowCode.DesignEngine.Repository.JsonFile.csproj" />
    <ProjectReference Include="..\..\..\LowCode\DesignEngine\H.LowCode.DesignEngine.Repository.RemoteService\H.LowCode.DesignEngine.Repository.RemoteService.csproj" />
    <!-- Workbench -->
    <ProjectReference Include="..\..\..\LowCode\DesignEngine\H.LowCode.Workbench\H.LowCode.Workbench.csproj" />
    <!-- RenderEngine 模块 -->
    <ProjectReference Include="..\..\..\LowCode\RenderEngine\H.LowCode.RenderEngine.Application\H.LowCode.RenderEngine.Application.csproj" />
    <ProjectReference Include="..\..\..\LowCode\RenderEngine\H.LowCode.RenderEngine.EntityFrameworkCore\H.LowCode.RenderEngine.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\LowCode\RenderEngine\H.LowCode.RenderEngine.Repository.JsonFile\H.LowCode.RenderEngine.Repository.JsonFile.csproj" />
    <ProjectReference Include="..\..\..\LowCode\RenderEngine\H.LowCode.RenderEngine.Repository.RemoteService\H.LowCode.RenderEngine.Repository.RemoteService.csproj" />
    <!-- Themes -->
    <ProjectReference Include="..\..\..\LowCode\RenderEngine\H.LowCode.Themes.AntBlazor\H.LowCode.Themes.AntBlazor.csproj" />
    <!-- Approval 模块 -->
    <ProjectReference Include="..\..\..\Services\Approval\H.Approval.Application\H.Approval.Application.csproj" />
  </ItemGroup>
</Project>