<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../../../common.props" />

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Application" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\H.Organization.Application.Contracts\H.Organization.Application.Contracts.csproj" />
    <ProjectReference Include="..\H.Organization.Domain\H.Organization.Domain.csproj" />
    <ProjectReference Include="..\H.Organization.EntityFrameworkCore\H.Organization.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\Account\H.Account.Application.Contracts\H.Account.Application.Contracts.csproj" />
  </ItemGroup>
</Project>
