<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../common.props" />
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Application.Contracts" />
    <PackageReference Include="Volo.Abp.Identity.Application.Contracts" />
    <PackageReference Include="Volo.Abp.Account.Application.Contracts" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\SystemPortal\H.SystemPortal.Application.Contracts\H.SystemPortal.Application.Contracts.csproj" />
  </ItemGroup>
</Project>