<Project Sdk="Microsoft.NET.Sdk.Razor">
	<Import Project="../../../common.props" />
	
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="AntDesign" />
  </ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\H.AutoTest.Application.Contracts\H.AutoTest.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Admin\H.Admin.AppDrawer\H.Admin.AppDrawer.csproj" />
  </ItemGroup>

</Project>
