<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../common.props" />
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Application" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Utils\H.Extensions.System\H.Extensions.System.csproj" />
    <ProjectReference Include="..\..\..\Components\AppDrawer\H.AppDrawer.Model\H.AppDrawer.Model.csproj" />
  </ItemGroup>
</Project>
