<Project Sdk="Microsoft.NET.Sdk">
	
  <Import Project="../../../common.props" />
	
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\H.Organization.Application.Contracts\H.Organization.Application.Contracts.csproj" />
  </ItemGroup>
</Project>
