<Project Sdk="Microsoft.NET.Sdk.Razor">
  <Import Project="../../../common.props" />
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Enterprise\H.Enterprise.Application.Contracts\H.Enterprise.Application.Contracts.csproj" />
    <ProjectReference Include="..\H.SystemPortal.Application.Contracts\H.SystemPortal.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Components\AppDrawer\H.AppDrawer.Model\H.AppDrawer.Model.csproj" />
    <ProjectReference Include="..\..\..\Utils\H.Util.Blazor\H.Util.Blazor.csproj" />
  </ItemGroup>
</Project>
