<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\common.props" />
	<ItemGroup>
	  <PackageReference Include="Volo.Abp.Ddd.Application.Contracts" />
	  <PackageReference Include="Volo.Abp.Validation" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Common\H.LowCode.Application.Contracts\H.LowCode.Application.Contracts.csproj" />
	  <ProjectReference Include="..\..\Common\H.LowCode.MetaSchema.DesignEngine\H.LowCode.MetaSchema.DesignEngine.csproj" />
	  <ProjectReference Include="..\H.LowCode.DesignEngine.Model\H.LowCode.DesignEngine.Model.csproj" />
	</ItemGroup>

</Project>
