<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <Import Project="..\..\..\common.props" />
  <PropertyGroup>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Volo.Abp.Autofac.WebAssembly" />
  </ItemGroup>
  <ItemGroup>
    <!-- Shared and Utils -->
    <ProjectReference Include="..\..\..\Components\AppDrawer\H.AppDrawer.Components\H.AppDrawer.Components.csproj" />
    <!-- Portal -->
    <ProjectReference Include="..\..\..\Services\Portal\H.Portal.Web\H.Portal.Web.csproj" />
    <!-- Account -->
    <ProjectReference Include="..\..\..\Services\Account\H.Account.Web\H.Account.Web.csproj" />
    <!-- Organization -->
    <ProjectReference Include="..\..\..\Services\Organization\H.Organization.Web\H.Organization.Web.csproj" />
    <!-- DesignEngine -->
    <ProjectReference Include="..\..\..\LowCode\DesignEngine\H.LowCode.Workbench\H.LowCode.Workbench.csproj" />
    <!-- RenderEngine -->
    <ProjectReference Include="..\..\..\LowCode\RenderEngine\H.LowCode.Themes.AntBlazor\H.LowCode.Themes.AntBlazor.csproj" />
    <!-- Approval -->
    <ProjectReference Include="..\..\..\Services\Approval\H.Approval.Web\H.Approval.Web.csproj" />
    <!-- AutoTest -->
    <ProjectReference Include="..\..\..\Services\AutoTest\H.AutoTest.Web\H.AutoTest.Web.csproj" />
  </ItemGroup>
</Project>