<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <Import Project="..\..\..\common.props" />
	
  <PropertyGroup>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Volo.Abp.Autofac.WebAssembly" />
    <PackageReference Include="Volo.Abp.Http.Client" />
  </ItemGroup>

  <ItemGroup>
    <!-- Portal -->
    <ProjectReference Include="..\..\..\Admin\H.LowCode.Portal\H.LowCode.Portal.csproj" />
    <!-- Account -->
    <ProjectReference Include="..\..\..\Services\Account\H.Account.Web\H.Account.Web.csproj" />
    <ProjectReference Include="..\..\..\Services\Account\H.Account.Client\H.Account.Client.csproj" />
    <!-- Organization -->
    <ProjectReference Include="..\..\..\Services\Organization\H.Organization.Web\H.Organization.Web.csproj" />
    <ProjectReference Include="..\..\..\Services\Organization\H.Organization.Client\H.Organization.Client.csproj" />
    <!-- DesignEngine -->
    <ProjectReference Include="..\..\..\LowCode\DesignEngine\H.LowCode.DesignEngine\H.LowCode.DesignEngine.csproj" />
    <ProjectReference Include="..\..\..\LowCode\DesignEngine\H.LowCode.Workbench\H.LowCode.Workbench.csproj" />
    <!-- RenderEngine (Themes.AntBlazor) -->
    <ProjectReference Include="..\..\..\LowCode\RenderEngine\H.LowCode.Themes.AntBlazor\H.LowCode.Themes.AntBlazor.csproj" />
    <!-- Shared and Utils -->
    <ProjectReference Include="..\H.LowCode.Host.All.Shared\H.LowCode.Host.All.Shared.csproj" />
    <ProjectReference Include="..\..\..\Utils\H.Util.Blazor\H.Util.Blazor.csproj" />
  </ItemGroup>

</Project>
