<Project Sdk="Microsoft.NET.Sdk.Razor">
  <Import Project="..\..\..\common.props" />
  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="Microsoft.AspNetCore.Http" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Components\AppDrawer\H.AppDrawer.Components\H.AppDrawer.Components.csproj" />
    <ProjectReference Include="..\..\..\Utils\H.Util.Blazor\H.Util.Blazor.csproj" />
    <ProjectReference Include="..\..\..\Utils\H.Util.Ids\H.Util.Ids.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Common\H.LowCode.ComponentBase\H.LowCode.ComponentBase.csproj" />
    <ProjectReference Include="..\..\Common\H.LowCode.MetaSchema.DesignEngine\H.LowCode.MetaSchema.DesignEngine.csproj" />
    <ProjectReference Include="..\H.LowCode.DesignEngine.Application.Contracts\H.LowCode.DesignEngine.Application.Contracts.csproj" />
  </ItemGroup>
</Project>