<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="../../../../common.props" />
	<PropertyGroup>
		<RootNamespace>H.YunXiaoMcpServer</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ModelContextProtocol" />
		<PackageReference Include="ModelContextProtocol.AspNetCore" />
		<PackageReference Include="Volo.Abp.Core" />
		<PackageReference Include="Microsoft.Extensions.Http" />
	</ItemGroup>
</Project>
