<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../common.props" />
  <ItemGroup>
    <PackageReference Include="Elsa" />
    <PackageReference Include="Elsa.Workflows.Api" />
    <PackageReference Include="Elsa.Workflows.Core" />
    <PackageReference Include="Elsa.Persistence.EFCore.SqlServer" />
    <PackageReference Include="Volo.Abp.Ddd.Application" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\H.Approval.Application.Contracts\H.Approval.Application.Contracts.csproj" />
    <ProjectReference Include="..\H.Approval.EntityFrameworkCore\H.Approval.EntityFrameworkCore.csproj" />
  </ItemGroup>
</Project>
