<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../common.props" />
  <PropertyGroup>
    <RootNamespace>H.Notification.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" />
    <PackageReference Include="Volo.Abp.AutoMapper" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\H.Notification.Application.Contracts\H.Notification.Application.Contracts.csproj" />
    <ProjectReference Include="..\H.Notification.EntityFrameworkCore\H.Notification.EntityFrameworkCore.csproj" />
  </ItemGroup>

</Project>
