<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../common.props" />
  <ItemGroup>
    <PackageReference Include="Volo.Abp.EntityFrameworkCore" />
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Volo.Abp.Identity.EntityFrameworkCore" />
    <PackageReference Include="Volo.Abp.SettingManagement.EntityFrameworkCore" />
    <PackageReference Include="Volo.Abp.Identity.Domain" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
  </ItemGroup>
</Project>