<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../common.props" />
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Application" />
    <PackageReference Include="Volo.Abp.Identity.Application" />
    <PackageReference Include="Volo.Abp.Account.Application" />
    <PackageReference Include="Volo.Abp.SettingManagement.Domain" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\H.Account.Application.Contracts\H.Account.Application.Contracts.csproj" />
    <ProjectReference Include="..\H.Account.EntityFrameworkCore\H.Account.EntityFrameworkCore.csproj" />
  </ItemGroup>
</Project>