<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../common.props" />
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Application.Contracts" />
    <PackageReference Include="Volo.Abp.Identity.Application.Contracts" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Components\AppDrawer\H.AppDrawer.Model\H.AppDrawer.Model.csproj" />
  </ItemGroup>
</Project>
