<Project Sdk="Microsoft.NET.Sdk.Razor">
  <Import Project="..\..\common.props" />
  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="Volo.Abp.Ddd.Application" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Admin\H.Admin.AppDrawer\H.Admin.AppDrawer.csproj" />
  </ItemGroup>
</Project>