<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../common.props" />
  <PropertyGroup>
    <RootNamespace>H.Assistant.EntityFrameworkCore</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\H.Assistant.Application.Contracts\H.Assistant.Application.Contracts.csproj" />
  </ItemGroup>

</Project>
