<Project Sdk="Microsoft.NET.Sdk.Razor">
  <Import Project="../../../common.props" />
  <ItemGroup>
    <PackageReference Include="AntDesign.ProLayout" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\H.SystemManagement.Application.Contracts\H.SystemManagement.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Components\AppDrawer\H.AppDrawer.Components\H.AppDrawer.Components.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
</Project>
