<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../common.props" />
  <ItemGroup>
    <ProjectReference Include="../../../Utils/H.Abstractions/H.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Components\AppDrawer\H.AppDrawer.Model\H.AppDrawer.Model.csproj" />
  </ItemGroup>
</Project>
