<Project Sdk="Microsoft.NET.Sdk.Razor">

	<Import Project="..\..\common.props" />

	<ItemGroup>
		<SupportedPlatform Include="browser" />
		<PackageReference Include="H.Util.Ids" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AntDesign" />
		<PackageReference Include="H.Util.Blazor" />
		<PackageReference Include="Microsoft.Extensions.Http" />
		<PackageReference Include="System.Net.Http.Json" />
		<PackageReference Include="Volo.Abp.Core" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Common\H.LowCode.MetaSchema.DesignEngine\H.LowCode.MetaSchema.DesignEngine.csproj" />
		<ProjectReference Include="..\H.LowCode.DesignEngineBase\H.LowCode.DesignEngineBase.csproj" />
		<ProjectReference Include="..\H.LowCode.DesignEngine.Application.Contracts\H.LowCode.DesignEngine.Application.Contracts.csproj" />
		<ProjectReference Include="..\H.LowCode.DesignEngine.Model\H.LowCode.DesignEngine.Model.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Pages\ThemeParts\" />
	</ItemGroup>

</Project>
