<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\common.props" />
  <ItemGroup>
    <ProjectReference Include="..\..\..\Utils\H.Abstractions\H.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\Utils\H.Extensions.System\H.Extensions.System.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\H.LowCode.MetaSchema\H.LowCode.MetaSchema.csproj" />
  </ItemGroup>
</Project>