<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\common.props" />
  <ItemGroup>
    <ProjectReference Include="..\..\..\Utils\H.Abp.Application.Contracts\H.Abp.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Utils\H.Util.Base\H.Util.Base.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\H.LowCode.MetaSchema\H.LowCode.MetaSchema.csproj" />
  </ItemGroup>
</Project>