<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../../../common.props" />

  <ItemGroup>
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" />
    <PackageReference Include="Volo.Abp.Autofac" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\H.Account.Application\H.Account.Application.csproj" />
  </ItemGroup>
</Project>
