<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\common.props" />
  <ItemGroup>
    <PackageReference Include="Volo.Abp.AutoMapper" />
    <PackageReference Include="Volo.Abp.Core" />
    <PackageReference Include="Volo.Abp.Ddd.Application" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Common\H.LowCode.Application.Contracts\H.LowCode.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\Common\H.LowCode.ComponentBase\H.LowCode.ComponentBase.csproj" />
    <ProjectReference Include="..\..\Common\H.LowCode.Configuration\H.LowCode.Configuration.csproj" />
    <ProjectReference Include="..\H.LowCode.RenderEngine.Application.Contracts\H.LowCode.RenderEngine.Application.Contracts.csproj" />
    <ProjectReference Include="..\H.LowCode.RenderEngine.Domain\H.LowCode.RenderEngine.Domain.csproj" />
  </ItemGroup>
</Project>