<Project Sdk="Microsoft.NET.Sdk.Razor">

	<Import Project="..\..\common.props" />

	<ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <ProjectReference Include="..\..\Admin\H.Admin.AppDrawer\H.Admin.AppDrawer.csproj" />
  </ItemGroup>

</Project>
