<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../common.props" />
  <PropertyGroup>
    <RootNamespace>H.AI.EntityFrameworkCore</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\H.AI.Application.Contracts\H.AI.Application.Contracts.csproj" />
  </ItemGroup>

</Project>
