<Project Sdk="Microsoft.NET.Sdk.Razor">
  <Import Project="../../../common.props" />
  <ItemGroup>
    <PackageReference Include="Markdig" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\H.Agent.Application.Contracts\H.Agent.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Components\AppDrawer\H.AppDrawer.Components\H.AppDrawer.Components.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
</Project>
