<Project Sdk="Microsoft.NET.Sdk.Razor">
  <Import Project="../../../common.props" />
  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Components\AppDrawer\H.AppDrawer.Components\H.AppDrawer.Components.csproj" />
    <ProjectReference Include="..\H.Portal.Application.Contracts\H.Portal.Application.Contracts.csproj" />
  </ItemGroup>
</Project>