<Project Sdk="Microsoft.NET.Sdk.Razor">

  <Import Project="../../../common.props" />

  <ItemGroup>
    <PackageReference Include="Volo.Abp.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="AntDesign.ProLayout" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\H.Account.Application.Contracts\H.Account.Application.Contracts.csproj" />
    <ProjectReference Include="..\H.Account.Client\H.Account.Client.csproj" />
  </ItemGroup>
</Project>
