<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../common.props" />
  <PropertyGroup>
    <RootNamespace>H.SupplyChain.Application.Contracts</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Application.Contracts" />
    <PackageReference Include="Volo.Abp.Authorization" />
  </ItemGroup>

</Project>