<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../common.props" />
  <PropertyGroup>
    <RootNamespace>H.SupplyChain.Application.Contracts</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../Utils/H.Abstractions/H.Abstractions.csproj" />
  </ItemGroup>
</Project>
