<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../common.props" />
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Application" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\H.Enterprise.Application.Contracts\H.Enterprise.Application.Contracts.csproj" />
    <ProjectReference Include="..\H.Enterprise.EntityFrameworkCore\H.Enterprise.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\Services\Account\H.Account.Application.Contracts\H.Account.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\SystemPortal\H.SystemPortal.Application.Contracts\H.SystemPortal.Application.Contracts.csproj" />
  </ItemGroup>
</Project>
