<Project Sdk="Microsoft.NET.Sdk.Web">

	<Import Project="../../../../common.props" />

	<PropertyGroup>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Volo.Abp.Autofac" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
	</ItemGroup>

	<ItemGroup>
    <ProjectReference Include="../../../../Services/Organization/H.Organization.HttpApi/H.Organization.HttpApi.csproj" />
    <ProjectReference Include="../H.Organization.Host.Client/H.Organization.Host.Client.csproj" />
    <ProjectReference Include="../../../../Services/Account/H.Account.Application.Contracts/H.Account.Application.Contracts.csproj" />
  </ItemGroup>

</Project>
