<Project Sdk="Microsoft.NET.Sdk.Web">
  <Import Project="..\..\..\common.props" />
	
  <PropertyGroup>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>
	
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
    <PackageReference Include="Volo.Abp.Autofac" />
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" />
    <PackageReference Include="Volo.Abp.MultiTenancy" />
    <PackageReference Include="Volo.Abp.AspNetCore.MultiTenancy" />
  </ItemGroup>
	
  <ItemGroup>
    <!-- Client -->
    <ProjectReference Include="..\H.AppLab.Web.Host.Client\H.AppLab.Web.Host.Client.csproj" />
    <!-- DesignEngine -->
    <ProjectReference Include="..\..\..\LowCode\DesignEngine\H.LowCode.DesignEngine.Application\H.LowCode.DesignEngine.Application.csproj" />
    <ProjectReference Include="..\..\..\LowCode\DesignEngine\H.LowCode.DesignEngine.EntityFrameworkCore\H.LowCode.DesignEngine.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\LowCode\DesignEngine\H.LowCode.DesignEngine.Repository.JsonFile\H.LowCode.DesignEngine.Repository.JsonFile.csproj" />
    <ProjectReference Include="..\..\..\LowCode\DesignEngine\H.LowCode.DesignEngine.Repository.RemoteService\H.LowCode.DesignEngine.Repository.RemoteService.csproj" />
    <!-- RenderEngine -->
    <ProjectReference Include="..\..\..\LowCode\RenderEngine\H.LowCode.RenderEngine.Application\H.LowCode.RenderEngine.Application.csproj" />
    <ProjectReference Include="..\..\..\LowCode\RenderEngine\H.LowCode.RenderEngine.EntityFrameworkCore\H.LowCode.RenderEngine.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\LowCode\RenderEngine\H.LowCode.RenderEngine.Repository.JsonFile\H.LowCode.RenderEngine.Repository.JsonFile.csproj" />
    <ProjectReference Include="..\..\..\LowCode\RenderEngine\H.LowCode.RenderEngine.Repository.RemoteService\H.LowCode.RenderEngine.Repository.RemoteService.csproj" />
    <!-- Account -->
    <ProjectReference Include="..\..\..\Services\Account\H.Account.Application\H.Account.Application.csproj" />
    <!-- Assistant -->
    <ProjectReference Include="..\..\..\Agent\Assistant\H.Assistant.Application\H.Assistant.Application.csproj" />
    <!-- MCP Servers -->
    <ProjectReference Include="..\..\..\Agent\McpServers\H.Mcp.YunXiao\H.Mcp.YunXiao.csproj" />
    <!-- Organization -->
    <ProjectReference Include="..\..\..\Services\Organization\H.Organization.Application\H.Organization.Application.csproj" />
    <!-- Approval -->
    <ProjectReference Include="..\..\..\Services\Approval\H.Approval.Application\H.Approval.Application.csproj" />
    <!-- Testing -->
    <ProjectReference Include="..\..\..\Services\Testing\H.Testing.Application\H.Testing.Application.csproj" />
	<!-- Portal -->
    <ProjectReference Include="..\..\..\Services\Portal\H.Portal.Application\H.Portal.Application.csproj" />
    <!-- SystemPortal -->
    <ProjectReference Include="..\..\..\System\SystemPortal\H.SystemPortal.Application\H.SystemPortal.Application.csproj" />
    <!-- Notification -->
    <ProjectReference Include="..\..\..\Services\Notification\H.Notification.Application\H.Notification.Application.csproj" />
    <ProjectReference Include="..\..\..\Services\Notification\H.Notification.EntityFrameworkCore\H.Notification.EntityFrameworkCore.csproj" />
    <!-- Enterprise -->
    <ProjectReference Include="..\..\..\System\Enterprise\H.Enterprise.Application\H.Enterprise.Application.csproj" />
    <!-- Order -->
    <ProjectReference Include="..\..\..\Services\Order\H.Order.Application\H.Order.Application.csproj" />
    <ProjectReference Include="..\..\..\Services\Order\H.Order.EntityFrameworkCore\H.Order.EntityFrameworkCore.csproj" />
    <!-- Setting（配置管理） -->
    <ProjectReference Include="..\..\..\Services\Setting\H.Setting.Application\H.Setting.Application.csproj" />
    <ProjectReference Include="..\..\..\Services\Setting\H.Setting.EntityFrameworkCore\H.Setting.EntityFrameworkCore.csproj" />
    <!-- SupplyChain -->
    <ProjectReference Include="..\..\..\Services\SupplyChain\H.SupplyChain.Application\H.SupplyChain.Application.csproj" />
    <ProjectReference Include="..\..\..\Services\SupplyChain\H.SupplyChain.EntityFrameworkCore\H.SupplyChain.EntityFrameworkCore.csproj" />
    <!-- BackgroundTask -->
    <ProjectReference Include="..\..\..\Services\BackgroundTask\H.BackgroundTask.Application\H.BackgroundTask.Application.csproj" />
    <ProjectReference Include="..\..\..\Services\BackgroundTask\H.BackgroundTask.EntityFrameworkCore\H.BackgroundTask.EntityFrameworkCore.csproj" />
    <!-- File（文件管理） -->
    <ProjectReference Include="..\..\..\Services\File\H.File.Application\H.File.Application.csproj" />
    <ProjectReference Include="..\..\..\Services\File\H.File.EntityFrameworkCore\H.File.EntityFrameworkCore.csproj" />
  </ItemGroup>
</Project>