<Project Sdk="Microsoft.NET.Sdk.Razor">
  <Import Project="..\..\common.props" />
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Utils\H.Extensions.System\H.Extensions.System.csproj" />
  </ItemGroup>
</Project>