<Project Sdk="Microsoft.NET.Sdk.Razor">
	
  <Import Project="../../../common.props" />
	
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="System.Net.Http.Json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\H.Organization.Application.Contracts\H.Organization.Application.Contracts.csproj" />
    <ProjectReference Include="..\H.Organization.Client\H.Organization.Client.csproj" />
  </ItemGroup>
</Project>
