<Project Sdk="Microsoft.NET.Sdk.Razor">
	
  <Import Project="../../../common.props" />
	
  <ItemGroup>
    <PackageReference Include="AntDesign.ProLayout" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="System.Net.Http.Json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\H.Organization.Application.Contracts\H.Organization.Application.Contracts.csproj" />
    <ProjectReference Include="..\H.Organization.Client\H.Organization.Client.csproj" />
    <!-- Host.All.Shared for AppStateManager -->
    <ProjectReference Include="..\..\..\Host\H.LowCode.Host.All\H.LowCode.Host.All.Shared\H.LowCode.Host.All.Shared.csproj" />
    <!-- H.Util.Blazor for AppDrawer -->
    <ProjectReference Include="..\..\..\Utils\H.Util.Blazor\H.Util.Blazor.csproj" />
  </ItemGroup>
</Project>
