<Project Sdk="Microsoft.NET.Sdk.Razor">
  <Import Project="../../../common.props" />
  <ItemGroup>
    <PackageReference Include="AntDesign.ProLayout" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Admin\H.Admin.AppDrawer\H.Admin.AppDrawer.csproj" />
    <ProjectReference Include="..\H.Organization.Application.Contracts\H.Organization.Application.Contracts.csproj" />
  </ItemGroup>
</Project>