<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="../../../common.props" />

  <ItemGroup>
    <ProjectReference Include="..\H.AutoTest.Application.Contracts\H.AutoTest.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Utils\H.Util.Ids\H.Util.Ids.csproj" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Volo.Abp.Ddd.Application" />
		<PackageReference Include="Volo.Abp.AutoMapper" />
		<PackageReference Include="Microsoft.Playwright" />
		<PackageReference Include="Microsoft.AspNetCore.Http" />
	</ItemGroup>

</Project>
